### ISSUE TITLE
Fix criticial security vulnerability

### ISSUE THREAD

**Issue by BjoernPetersen** [woog-life/scrapers#26]
https://github.com/woog-life/scrapers/security/dependabot/5

🚨 We're obviously very vulnerable to DDoS attacks because of this issue, so this should be fixed ASAP. The dependabot description said something about memory, so I figure this would be resolved by using Rust.

**Comment by torbencarstens** [comment]
As soon as there is a new scrapy version (we're on the newest one) renovate will create an update PR, we have to wait until then.

**Comment by BjoernPetersen** [comment]
I don't get it. How can we possibly resolve a memory-related issue without Rust?

**Comment by torbencarstens** [comment]
Obviously it'll be using https://github.com/PyO3/pyo3 for the security fix and call rust internally, only way really

**Comment by torbencarstens** [comment]
closed by https://github.com/woog-life/scrapers/commit/39ca9e14d6af3ee292f8a0b7a7005ffb8dd3d27a
